Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> Zz×hÌ·Tó˜Â£¦kÚå¿’ŒðI–\Š¼‘«Ùº2Ž…J9–£@´á+Pð<Aukú´á\t%õŒÓˆ)M¸¨è8¿ÏýÜ
?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> +=®ÍSØ½#5¢ÜhÝÞ åZû;9æÉÆÑ§.±™7x7l¬ÁÁý¹°k6=ÅŽ¨Ûï«U7#´n±¾údÂÛ'¥žs¯ v±öNÈ®!Ð?
?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Unknown argument '³˜IÉíz¤h'.
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Unknown argument 'Sh›pµõß+¦æÀÉdG·‹à4WïÚ'.
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> ¶wD&›ÜpAÕ
?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> -¥C$ cCŠ¥ù\·wá":/øeËvH‰1B@­NRW""
?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> 
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> ?Invalid command
telnet> Connection closed.
